### ISSUE TITLE
Missed fields

### ISSUE THREAD

**Issue by andre719mv** [AckeeCZ/OpenGoogleSignInSDK#2]
Hi!
I am not able to read user name and email from GoogleUser. Is it possible to add this fields?

**Comment by IgorRosocha** [comment]
Hello @andre719mv!

First of all, thank you for your interest in using `OpenGoogleSignInSDK`. Further implementation is required for `GoogleUser` to support profile fields. We will take a look at it as soon as possible and make it a part of future release!
